### ISSUE TITLE
Cannot upload file without content-type

### ISSUE THREAD

**Issue by AJIOB** [crycode-de/http-server-upload#31]
I need to upload a big file, that is output of the another program.

# Current behavior

If I call `cat "${FILE}" | curl -F "uploads=@-;filename=test-file1" "http://x.x.x.x:8080/upload"`, the server answers with a message **File uploaded!**, but the file is not saved on a disk: neither new rows are provided here nor file presented on disk

![image](https://github.com/crycode-de/http-server-upload/assets/19916290/3d984ea4-4649-40a2-b014-b93376222ba1)

Bad upload Wireshark session: [upload-bad.zip](https://github.com/crycode-de/http-server-upload/files/12474023/upload-bad.zip)

HTTP headers:
![image](https://github.com/crycode-de/http-server-upload/assets/19916290/6334790d-25ba-492c-982f-fbf79e15883a)

# Temporary fix

If I manually set **Content-Type** header for the file, all works nice.

Command to upload file: `cat "${FILE}" | curl -F "uploads=@-;filename=test-file2;type=application/octet-stream" "http://x.x.x.x:8080/upload"`

Good upload Wireshark session: [upload-good.zip](https://github.com/crycode-de/http-server-upload/files/12473952/upload-good.zip)

HTTP headers:
![image](https://github.com/crycode-de/http-server-upload/assets/19916290/7c8d4c76-f7e1-4410-a82c-408eb100ecc7)

# Expected behavior

File can be uploaded with and without **Content-Type** header in a **multipart/form-data** part.

**Comment by crycode-de** [comment]
Thank you for opening this issue and the detailed description.

I've analyzed the problem and as I figured out it's as intended by design of the used [formidable](https://github.com/node-formidable/formidable) module. Maybe it's according to the http specs but I'm not sure.
Without a Content-Type provided, the multipart part is parsed as a form field with a string decoder. See [this comments in the formidable code](https://github.com/node-formidable/formidable/blob/master/src/Formidable.js#L320-L330) for details.

However, we have two issues here:

1. The message **File uploaded** isn't correct in this case. Here an error should be returned instead.
2. In the documentation should be mentioned that you need to provide the files Content-Type for piped uploads. (For uploads from saved files, the Content-Type is set automatically by curl.)

**Comment by crycode-de** [comment]
Just released [v3.0.0](https://github.com/crycode-de/http-server-upload/releases/tag/v3.0.0) containing a fix for for the wrong "ok" response and an updated readme mentioning piped upload together with some other changes.
